
name = "shorten"
compatibility_date = "2023-11-20"
main = "workers-site/index.js"

workers_dev = false

# here is the place to bound the custom domain that you want
route = { pattern = "revyth.com", custom_domain = true }


kv_namespaces = [
    { binding = "SHORTEN", id = "bc264f9d88cb41b1bc7b3028561b7faa", preview_id = "33d4f6d36e824e00b045732efb79cab5" }
]

[site]
bucket = "./public"

